language: java
jdk:
  - oraclejdk8

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -c 'create extension pgcrypto;' -U postgres
  - psql -c 'create extension hstore;' -U postgres
  - psql -c 'create extension postgis;' -U postgres
  - psql -c 'create database unit;' -U postgres

env:
  - EBEAN_DB=h2
  - EBEAN_DB=pg

after_failure:
  - ./.travis/print_surefire_reports

cache:
  directories:
  - $HOME/.m2
